### ISSUE TITLE
Kindly help to solve the following error

### ISSUE THREAD

**Issue by mislam5285** [ram-compbio/CANDO#9]
Kindly help to solve the following error:
Generating CANDO matrix...
Traceback (most recent call last):

  File "/tmp/ipykernel_3652/1890496437.py", line 10, in <module>
    lig_name=False, ncpus=ncpus)

  File "/home/mi/anaconda3/lib/python3.7/site-packages/cando/cando.py", line 4224, in generate_matrix
    p_dict[p[0]] = list(zip(p[1].split(','),p[2].split(',')))

IndexError: tuple index out of range

**Comment by zfalls** [comment]
@mislam5285 What protein library are you using when you run this code? 

This might be another case where you nee to re-download the libraries to make sure all of the files are complete.
